Repository PROJECT-X-REFRESH/Back-Reborn, pull requests merged in 2025-05, with the labels that each got.

#28 feat : login by deeplink
  src/main/java/com/reborn/back/global/config/WebSecurityConfig.java
  src/main/java/com/reborn/back/login/auth/controller/TokenController.java
  src/main/java/com/reborn/back/login/auth/utils/OAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: 📬 API, ✨ Feature

#33 Feat: FCM
  src/main/java/com/reborn/back/ReBornBackApplication.java
  src/main/java/com/reborn/back/comment/service/CommentService.java
  src/main/java/com/reborn/back/fcm/controller/FcmController.java
  src/main/java/com/reborn/back/fcm/dto/FcmMessageDto.java
  src/main/java/com/reborn/back/fcm/dto/FcmRequestDto.java
  src/main/java/com/reborn/back/fcm/service/FcmService.java
  src/main/java/com/reborn/back/fcm/service/PetAnniversaryScheduler.java
  src/main/java/com/reborn/back/global/config/SwaggerConfig.java
  src/main/java/com/reborn/back/login/repository/UserRepository.java
Labels: ✨ Feature

#34 Refactor: Redirect URL 수정
  src/main/resources/application.yml
Labels: 🔨 Refactor

#55 Feature: Hospital Evaluation Data
  src/main/java/com/reborn/back/global/api/SuccessCode.java
  src/main/java/com/reborn/back/global/utils/GCPMap/GooglePlacesService.java
  src/main/java/com/reborn/back/global/utils/hira/HiraEvaluationService.java
  src/main/java/com/reborn/back/global/utils/hira/HiraInfoService.java
  src/main/java/com/reborn/back/review/farewell/controller/RecognizeController.java
  src/main/java/com/reborn/back/review/farewell/dto/CounselingCenterDto.java
  src/main/java/com/reborn/back/review/farewell/service/RecognizeService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#56 Refactor: Update Board and Read ALL(without category) List of Board
  src/main/java/com/reborn/back/board/controller/BoardController.java
  src/main/java/com/reborn/back/board/repository/BoardRepository.java
  src/main/java/com/reborn/back/board/service/BoardService.java
Labels: 🔨 Refactor
