Repository PROJECT-X-REFRESH/Back-Reborn, pull requests merged in 2025-03, with the labels that each got.

#17 Feature : login
  build.gradle
  src/main/java/com/reborn/back/domain/board/BoardView.java
  src/main/java/com/reborn/back/domain/chat/ChatMessage.java
  src/main/java/com/reborn/back/domain/chat/ChatRoom.java
  src/main/java/com/reborn/back/domain/chat/ChatRoomStatus.java
  src/main/java/com/reborn/back/domain/counseller/Counseller.java
  src/main/java/com/reborn/back/domain/entity/Address.java
  src/main/java/com/reborn/back/domain/entity/Emotion.java
  src/main/java/com/reborn/back/domain/entity/EmotionState.java
  src/main/java/com/reborn/back/domain/entity/OrganizeType.java
  src/main/java/com/reborn/back/domain/review/farewell/Rebirth.java
  src/main/java/com/reborn/back/domain/review/farewell/Remember.java
  src/main/java/com/reborn/back/domain/user/OAuth.java
  src/main/java/com/reborn/back/domain/user/User.java
  src/main/java/com/reborn/back/domain/user/UserInfo.java
  src/main/java/com/reborn/back/global/config/FirebaseConfig.java
  src/main/java/com/reborn/back/global/config/SwaggerConfig.java
  src/main/java/com/reborn/back/login/auth/controller/TokenController.java
  src/main/java/com/reborn/back/login/auth/jwt/AuthCreationFilter.java
  src/main/java/com/reborn/back/login/auth/mapper/CustomUserDetails.java
  src/main/java/com/reborn/back/login/auth/service/JpaUserDetailsManager.java
  src/main/java/com/reborn/back/login/auth/utils/OAuth2SuccessHandler.java
  src/main/java/com/reborn/back/login/auth/utils/OAuth2UserServiceImpl.java
  src/main/java/com/reborn/back/login/controller/UserController.java
  src/main/java/com/reborn/back/login/mapper/UserConverter.java
  src/main/java/com/reborn/back/login/repository/OAuthRepository.java
  src/main/java/com/reborn/back/login/repository/UserInfoRepository.java
  src/main/java/com/reborn/back/login/repository/UserRepository.java
  src/main/java/com/reborn/back/login/service/UserService.java
Labels: 🐞 BugFix, 🔨 Refactor

#18 Feature : Pet and human profile
  src/main/java/com/reborn/back/aiPost/controller/aiPostController.java
  src/main/java/com/reborn/back/aiPost/repository/AiPostBookmarkRepository.java
  src/main/java/com/reborn/back/aiPost/repository/AiPostLikeRepository.java
  src/main/java/com/reborn/back/aiPost/repository/AiPostRepository.java
  src/main/java/com/reborn/back/aiPost/service/AiPostService.java
  src/main/java/com/reborn/back/domain/user/OAuth.java
  src/main/java/com/reborn/back/global/api/ApiResponse.java
  src/main/java/com/reborn/back/global/api/SuccessCode.java
  src/main/java/com/reborn/back/global/exception/GlobalExceptionHandler.java
  src/main/java/com/reborn/back/login/auth/mapper/CustomUserDetails.java
  src/main/java/com/reborn/back/login/auth/service/JpaUserDetailsManager.java
  src/main/java/com/reborn/back/login/auth/utils/OAuth2SuccessHandler.java
  src/main/java/com/reborn/back/login/controller/UserController.java
  src/main/java/com/reborn/back/login/dto/UserResponseDto.java
  src/main/java/com/reborn/back/login/mapper/UserConverter.java
  src/main/java/com/reborn/back/login/service/UserService.java
  src/main/java/com/reborn/back/pet/contoller/PetController.java
  src/main/java/com/reborn/back/pet/dto/PetRequestDto.java
  src/main/java/com/reborn/back/pet/dto/PetResponseDto.java
  src/main/java/com/reborn/back/pet/repository/PetRepository.java
  src/main/java/com/reborn/back/pet/service/PetService.java
  src/main/java/com/reborn/back/review/recollection/repository/RecordRepository.java
  src/main/java/com/reborn/back/review/recollection/repository/RemindRepository.java
  src/main/java/com/reborn/back/review/recollection/service/RecordService.java
  src/main/java/com/reborn/back/review/recollection/service/RemindService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🙋‍♂️ Question

#21 Refactor : CommentCount
  src/main/java/com/reborn/back/board/controller/BoardController.java
  src/main/java/com/reborn/back/board/service/BoardService.java
  src/main/java/com/reborn/back/comment/converter/CommentConverter.java
  src/main/java/com/reborn/back/comment/repository/CommentRepository.java
  src/main/java/com/reborn/back/comment/service/CommentService.java
  src/main/java/com/reborn/back/domain/comment/Comment.java
Labels: 🔨 Refactor

#22 Feature test
  src/main/java/com/reborn/back/domain/aiPost/AiPost.java
  src/main/java/com/reborn/back/domain/aiPost/AiPostBookmark.java
  src/main/java/com/reborn/back/domain/aiPost/AiPostLike.java
  src/main/java/com/reborn/back/domain/aiPost/AiPostView.java
  src/main/java/com/reborn/back/domain/board/Board.java
  src/main/java/com/reborn/back/domain/board/BoardLike.java
  src/main/java/com/reborn/back/domain/chat/ChatMessage.java
  src/main/java/com/reborn/back/domain/chat/ChatRoom.java
  src/main/java/com/reborn/back/domain/comment/Comment.java
  src/main/java/com/reborn/back/domain/pet/Pet.java
  src/main/java/com/reborn/back/domain/review/farewell/Farewell.java
  src/main/java/com/reborn/back/domain/review/farewell/Rebirth.java
  src/main/java/com/reborn/back/domain/review/farewell/Recognize.java
  src/main/java/com/reborn/back/domain/review/farewell/Remember.java
  src/main/java/com/reborn/back/domain/review/farewell/Reveal.java
  src/main/java/com/reborn/back/domain/user/OAuth.java
  src/main/java/com/reborn/back/domain/user/User.java
  src/main/java/com/reborn/back/global/exception/GeneralException.java
  src/main/java/com/reborn/back/login/auth/utils/OAuth2SuccessHandler.java
  src/main/java/com/reborn/back/login/service/UserService.java
  src/main/java/com/reborn/back/pet/dto/PetRequestDto.java
  src/main/java/com/reborn/back/pet/dto/PetResponseDto.java
  src/main/java/com/reborn/back/pet/service/PetService.java
  src/main/resources/application.yml
  src/test/java/com/reborn/back/board/service/BoardLikeServiceTest.java
  src/test/java/com/reborn/back/board/service/BoardServiceTest.java
  src/test/java/com/reborn/back/comment/service/CommentServiceTest.java
  src/test/java/com/reborn/back/login/service/UserServiceTest.java
  src/test/java/com/reborn/back/pet/service/PetServiceTest.java
Labels: 🔨 Refactor, ✅ Test
